[package]
name = "ggst-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
hex = "0.4"
regex = "1.5"
lazy_static = "1.4.0"
chrono = "0.4"
